# Generated by Django 6.0.2 on 2026-02-19 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('ssn_last_four', models.CharField(blank=True, help_text='Last 4 digits of SSN (PII)', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('settled', 'Settled'), ('dropped', 'Dropped'), ('trial', 'Trial'), ('closed', 'Closed')], default='open', max_length=20)),
                ('incident_type', models.CharField(choices=[('auto', 'Auto Accident'), ('slip_fall', 'Slip & Fall'), ('medical_malpractice', 'Medical Malpractice'), ('product_liability', 'Product Liability'), ('workplace', 'Workplace Injury'), ('other', 'Other')], default='other', max_length=30)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_location', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('outcome_status', models.CharField(blank=True, help_text='Final outcome label from transcript data', max_length=50)),
                ('outcome_value', models.DecimalField(blank=True, decimal_places=2, help_text='Settlement or award amount', max_digits=14, null=True)),
                ('statute_of_limitations_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='intake.client')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('phone', 'Phone Call'), ('in_person', 'In Person'), ('email', 'Email'), ('text', 'Text Message'), ('portal', 'Client Portal')], default='phone', max_length=20)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('raw_transcript', models.JSONField(blank=True, default=list, help_text='Array of transcript turn objects: [{speaker, text, timestamp}]')),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='ID from source system (e.g. sample_transcripts.json)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='intake.case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='intake.client')),
            ],
            options={
                'verbose_name': 'Client Communication',
                'verbose_name_plural': 'Client Communications',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientCommunicationCitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('citation_key', models.CharField(help_text="Semantic key, e.g. 'incident_date', 'at_fault_party'", max_length=100)),
                ('cited_text', models.TextField(help_text='The verbatim excerpt from the transcript supporting this citation')),
                ('turn_index', models.PositiveIntegerField(blank=True, help_text='Index into raw_transcript array', null=True)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Parser confidence 0.0–1.0')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='intake.clientcommunication')),
            ],
            options={
                'verbose_name': 'Client Communication Citation',
                'verbose_name_plural': 'Client Communication Citations',
                'ordering': ['citation_key', '-confidence_score'],
            },
        ),
        migrations.CreateModel(
            name='CitationReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(help_text='UUID of the referenced object', max_length=36)),
                ('relationship_label', models.CharField(blank=True, help_text="Human label for this reference, e.g. 'treating physician'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('citation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='intake.clientcommunicationcitation')),
            ],
            options={
                'verbose_name': 'Citation Reference',
                'verbose_name_plural': 'Citation References',
                'ordering': ['citation'],
            },
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('medical', 'Medical Expenses'), ('lost_wages', 'Lost Wages'), ('pain_suffering', 'Pain & Suffering'), ('property', 'Property Damage'), ('future_medical', 'Future Medical Expenses'), ('future_lost_wages', 'Future Lost Wages'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('documented', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='intake.case')),
            ],
            options={
                'verbose_name': 'Damage',
                'verbose_name_plural': 'Damages',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Law Firm',
                'verbose_name_plural': 'Law Firms',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='intake_lawf_name_046ec8_idx')],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='law_firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='intake.lawfirm'),
        ),
        migrations.CreateModel(
            name='MedicalFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(blank=True, help_text='e.g., hospital, urgent care, chiropractic', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('npi', models.CharField(blank=True, help_text='National Provider Identifier', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medical Facility',
                'verbose_name_plural': 'Medical Facilities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='intake_medi_name_f84efe_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicalProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('npi', models.CharField(blank=True, help_text='National Provider Identifier', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='intake.medicalfacility')),
            ],
            options={
                'verbose_name': 'Medical Provider',
                'verbose_name_plural': 'Medical Providers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OtherParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, help_text='e.g., at-fault driver, property owner', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_parties', to='intake.case')),
            ],
            options={
                'verbose_name': 'Other Party',
                'verbose_name_plural': 'Other Parties',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('claim_number', models.CharField(blank=True, max_length=100)),
                ('coverage_type', models.CharField(choices=[('liability', 'Liability'), ('uninsured_motorist', 'Uninsured Motorist'), ('medical_payments', 'Medical Payments'), ('health', 'Health'), ('workers_comp', 'Workers Compensation'), ('other', 'Other')], default='liability', max_length=30)),
                ('policy_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('adjuster_name', models.CharField(blank=True, max_length=255)),
                ('adjuster_phone', models.CharField(blank=True, max_length=50)),
                ('adjuster_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insured_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_providers', to='intake.client')),
                ('insured_other_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_providers', to='intake.otherparty')),
            ],
            options={
                'verbose_name': 'Insurance Provider',
                'verbose_name_plural': 'Insurance Providers',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('treatment_type', models.CharField(blank=True, help_text='e.g., ER visit, MRI, physical therapy', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('icd_codes', models.JSONField(blank=True, default=list, help_text='List of ICD-10 diagnosis codes')),
                ('billed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='intake.case')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='intake.medicalprovider')),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='intake_case_status_ed9b80_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['incident_date'], name='intake_case_inciden_f155ec_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_at'], name='intake_case_created_6a642e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['client'], name='intake_case_client__2dd546_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcommunication',
            index=models.Index(fields=['occurred_at'], name='intake_clie_occurre_a89552_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcommunication',
            index=models.Index(fields=['created_at'], name='intake_clie_created_46c451_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcommunication',
            index=models.Index(fields=['client'], name='intake_clie_client__300d03_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcommunication',
            index=models.Index(fields=['case'], name='intake_clie_case_id_a4f6de_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcommunicationcitation',
            index=models.Index(fields=['communication'], name='intake_clie_communi_065965_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcommunicationcitation',
            index=models.Index(fields=['citation_key', 'confidence_score'], name='intake_clie_citatio_c94e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='citationreference',
            index=models.Index(fields=['citation'], name='intake_cita_citatio_3f0cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='citationreference',
            index=models.Index(fields=['content_type', 'object_id'], name='intake_cita_content_6be3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='damage',
            index=models.Index(fields=['case'], name='intake_dama_case_id_2d52ee_idx'),
        ),
        migrations.AddIndex(
            model_name='damage',
            index=models.Index(fields=['category'], name='intake_dama_categor_dc526e_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['law_firm'], name='intake_clie_law_fir_61a3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_name', 'first_name'], name='intake_clie_last_na_88d959_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalprovider',
            index=models.Index(fields=['facility'], name='intake_medi_facilit_fb6a49_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalprovider',
            index=models.Index(fields=['last_name', 'first_name'], name='intake_medi_last_na_30ff53_idx'),
        ),
        migrations.AddIndex(
            model_name='otherparty',
            index=models.Index(fields=['case'], name='intake_othe_case_id_9997c9_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceprovider',
            index=models.Index(fields=['insured_client'], name='intake_insu_insured_177320_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceprovider',
            index=models.Index(fields=['insured_other_party'], name='intake_insu_insured_aa1443_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['case'], name='intake_trea_case_id_f33bed_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['provider'], name='intake_trea_provide_770a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['start_date'], name='intake_trea_start_d_fc6f37_idx'),
        ),
    ]
